version: '3.8'
name: dsa-cluster

services:
  #faz o build da imagem com o dockerfile se ela nao existir
  spark-master:
    container_name: dsa-spark-master
    build: .
    image: dsa-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./dados:/opt/spark/data
      - ./jobs:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'
    
  spark-history-server:
    container_name: dsa-spark-history
    image: dsa-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
  #Nao possui container name pois nao sabemos quantos workers vao ser criados, nesse caso ele vai colocar o nome do servico seguido de um numero incremental
  spark-worker:
    image: dsa-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./dados:/opt/spark/data
      - ./jobs:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
  
#Nao precisa mapear pois esta sendo mapeado dentro dos containers
volumes:
  spark-logs: